from datetime import datetime, timezone
from typing import List, Dict, Any, Tuple, Optional

class ThreadRuleService:
    """
    Dedicated service for rule-based heuristics, workflow status rules, 
    and extensible template policies.
    """

    def derive_workflow_status(
        self,
        thread: Dict[str, Any],
        emails: List[Dict[str, Any]],
        user_email: str,
        has_pending_tasks: bool,
        ignore_archived: bool = False
    ) -> str:
        """
        Derives thread workflow_status following docs/thread_workflow_and_labels_manifest.md:
        1. If has_pending_tasks -> 'needs_action' (includes open questions asked to user)
        2. If thread is already 'archived' and not ignore_archived -> preserve 'archived'
        3. If 0 pending tasks:
           - Check latest email:
             - If sent by user:
               - Elapsed time >= 48h -> 'follow_up' (SLA threshold)
               - Elapsed time < 48h -> 'awaiting_reply'
             - If third-party sender -> 'informational'
        """
        if has_pending_tasks:
            return "needs_action"

        if not ignore_archived and thread.get("workflow_status") == "archived":
            return "archived"

        if not emails:
            return "informational"

        latest_email = emails[0]
        latest_sender = (latest_email.get("sender") or "").lower()
        is_user_sender = bool(user_email and user_email.lower() in latest_sender)

        if is_user_sender:
            received_at_str = latest_email.get("received_at")
            hours_elapsed = 0.0
            if received_at_str:
                try:
                    sent_dt = datetime.fromisoformat(received_at_str.replace("Z", "+00:00"))
                    now_dt = datetime.now(timezone.utc)
                    hours_elapsed = (now_dt - sent_dt).total_seconds() / 3600.0
                except Exception:
                    hours_elapsed = 0.0

            if hours_elapsed >= 48.0:
                return "follow_up"
            else:
                return "awaiting_reply"

        return "informational"

    def generate_rule_based_fallback(
        self,
        thread: Dict[str, Any],
        emails: List[Dict[str, Any]]
    ) -> Tuple[Optional[str], str, bool]:
        """
        Rule-based fallback when LLM execution is bypassed or non-actionable.
        Returns: (summary, priority, does_need_auto_draft)
        """
        # 1. Summary: Preserve existing summary if already generated by LLM, else None
        summary = thread.get("summary")

        # 2. Priority: Keep existing priority or default to medium
        priority = thread.get("priority") or "medium"

        # 3. Auto draft heuristic: False for rule-based fallbacks
        does_need_auto_draft = False

        return summary, priority, does_need_auto_draft
